### ISSUE TITLE
`cffconvert=2.0.0` is not outputting fields like `grants` and `communities`

### ISSUE THREAD

**Issue by valeriupredoi** [citation-file-format/cff-converter-python#286]
Hi @jspaaks - first off many thanks for building and maintaining `cffconvert`, lots of us are happily using it :beer: Second, I wanted to ask you a quick question - as a newbie - am a software engineer but have relatively little experience with such things as Zenodo, I noticed that running 2.0.0 with `cffconvert --format zenodo --outfile .zenodo.json` - the output JSON file is correct syntactically and holds all the authors but removes stuff like `grants` or `communities` that the older version was writing to it; before the new version we were using it with a cmd line flag that is no more `cffconvert --ignore-suspect-keys --outputformat zenodo --outfile .zenodo.json` - could that be the case why we're missing those keys now? If so, is there a way to configure it to still accept and output to file those keys? Many thanks in advance, much appreciated :beers:

**Comment by jspaaks** [comment]
Hi @valeriupredoi, I'm pleased to hear you find `cffconvert` useful. As to your question, I don't think any previous versions of `cffconvert` included keys like `grants` in the result when converting to Zenodo metadata format. However, back then Zenodo, or more precisely the Zenodo-GitHub integration, ingested metadata from `.zenodo.json` (as well as from the GitHub API), whereas these days, it seems that Zenodo will only use data from `CITATION.cff` even if there is additional metadata available, for example as a `.zenodo.json`. This is a bit of a bummer, because in my view it will be a long time before `CITATION.cff` files can support as much metadata as what Zenodo metadata was able to. 

Is this consistent with the behavior that you are experiencing?

I'm in the process of writing up a workaround, which is currently a bit convoluted. The workaround involves changing to a locally run release script that talks to Zenodo's API using [`zenodraft`](https://www.npmjs.com/package/zenodraft). The workflow also combines metadata from `CITATION.cff` with additional data in Zenodo metadata format (which may include `grants` as well as other things, see the JSONSchema I made here https://github.com/zenodraft/zenodo-metadata-schema). You can find my notes on the workflow here: https://github.com/jspaaks/2022-ieee (skip everything until you see the section about zenodraft; check back in a week or so, it'll hopefully be done then :)

Hope this helps!
-Jurriaan

**Comment by valeriupredoi** [comment]
hi @jspaaks - this is great, many thanks for your detailed reply, it is very much our case at the moment - we had the `grants` section in the older `.zenodo.json` and it used to be preserved when the file was re-generated, but not no more now. I will link your reply and good news about a future workaround on to my colleagues, so that we can decide what's best to do for now. Very much appreciated for your time to write back, you can now close this issue by me, all understood now :beer:
