### ISSUE TITLE
Should @context be the CodeMeta schema instead of schema.org?

### ISSUE THREAD

**Issue by sdruskat** [citation-file-format/cff-converter-python#30]
This issue is referring to https://github.com/citation-file-format/cff-converter-python/blob/master/cff_converter_python/citation.py#L303:

CFF-Core can easily be represented in a pure schema.org contexted codemeta.json file. However, I think there are two reasons why it would perhaps make sense to change the context to `https://doi.org/10.5063/schema/codemeta-2.0` (cf. https://github.com/codemeta/codemeta/blob/master/codemeta.json#L2).

1. It makes the exported codemeta.json future-proof in that it doesn't require the user to change the `@context` value in order to use the CodeMeta fields that extend schema.org.
2. There are plans to extend CFF to cover the full field set of CodeMeta, in which case the converter (once it would include the new CFF "module") would produce invalid CodeMeta files if the context was left at schema.org.

On the other hand (cf. https://github.com/codemeta/codemeta/issues/180#issuecomment-375437906), "plain" schema.org files are "unknowingly compatible", hence I'm not sure what the best option would be here, and hence would like to hear your thoughts on this.

**Comment by jspaaks** [comment]
I am kind of on the fence on this. I do remember consciously changing the context from codemeta to schema.org because I realized I wasn't using any of the keys that codemeta adds. Additionally, I would like to be able to have an online validation tool to such as https://search.google.com/structured-data/testing-tool, which currently doesn't seem to understand either

```json-ld
  "@context": [
    "https://doi.org/10.5063/schema/codemeta-2.0",
    "http://schema.org"
  ],
```
or
```json-ld
  "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
```
or 
```json-ld
  "@context": "https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld",
```
However, after some more looking around, I found https://json-ld.org/playground/ which seems to be able to deal with e.g.
```json-ld
  "@context": [
    "https://doi.org/10.5063/schema/codemeta-2.0",
    "http://schema.org"
  ],
```

I guess another argument in favor of changing the context to codemeta is that [the function](https://github.com/citation-file-format/cff-converter-python/blob/b7505591cf421ab33156ec0bffb0af43fd7d2cd1/cff_converter_python/citation.py#L267) is advertised as exporting citation information to codemeta.
